# Generated by Django 6.1.1 on 2026-09-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_demo_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Astana city budget', max_length=120)),
                ('mode', models.CharField(choices=[('money', 'Money'), ('units', 'Units')], default='money', max_length=10)),
                ('currency', models.CharField(default='KZT', max_length=3)),
                ('money', models.JSONField()),
                ('units', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(default='KZT', max_length=3)),
                ('rates', models.JSONField()),
                ('source_updated_at', models.DateTimeField(null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': 'fetched_at',
            },
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Metric',
        ),
        migrations.DeleteModel(
            name='WaitlistSignup',
        ),
    ]
