# Generated by Django 6.1.1 on 2026-09-23 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_budget_planner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=10)),
                ('long_name', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=7)),
                ('fleet', models.PositiveSmallIntegerField()),
                ('vehicles_seen', models.PositiveSmallIntegerField()),
                ('trips_per_day', models.PositiveIntegerField()),
                ('peak_headway', models.FloatField()),
                ('avg_headway', models.FloatField()),
                ('trip_minutes', models.PositiveSmallIntegerField()),
                ('first_departure', models.CharField(max_length=5)),
                ('last_departure', models.CharField(max_length=5)),
                ('days_observed', models.PositiveSmallIntegerField()),
                ('shape', models.JSONField()),
            ],
            options={
                'ordering': ['short_name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=60)),
                ('name_kk', models.CharField(max_length=60)),
                ('population', models.PositiveIntegerField()),
                ('population_share', models.FloatField()),
                ('population_change', models.FloatField(null=True)),
                ('t1_congestion', models.PositiveSmallIntegerField(null=True)),
                ('t2_accessibility', models.PositiveSmallIntegerField(null=True)),
                ('color', models.CharField(max_length=7)),
                ('area_km2', models.FloatField()),
                ('bbox', models.JSONField()),
                ('outline', models.JSONField()),
                ('holes', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-population'],
            },
        ),
        migrations.CreateModel(
            name='TransportScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('source', models.CharField(choices=[('osm', 'OpenStreetMap'), ('zenodo', 'Zenodo GTFS')], max_length=10)),
                ('routes', models.JSONField(default=list)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_stops', to='core.district')),
            ],
        ),
        migrations.CreateModel(
            name='PopulationCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('population', models.FloatField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='core.district')),
            ],
        ),
        migrations.CreateModel(
            name='RailStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('name_en', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('rail', 'Railway'), ('lrt', 'LRT')], max_length=4)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rail_stations', to='core.district')),
            ],
        ),
    ]
