# Generated by Django 6.1.1 on 2026-09-23 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_transport'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreeneryScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='e1_green',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='GreenArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=10)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('area_m2', models.FloatField()),
                ('rings', models.JSONField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='green_areas', to='core.district')),
            ],
        ),
        migrations.CreateModel(
            name='GreenCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('park_m2', models.FloatField(default=0)),
                ('forest_m2', models.FloatField(default=0)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='green_cells', to='core.district')),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('species', models.CharField(blank=True, max_length=80)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trees', to='core.district')),
            ],
        ),
    ]
