# Generated by Django 6.1.1 on 2026-09-23 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_greenery'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceFigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=60, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=60)),
                ('data_year', models.CharField(blank=True, max_length=20)),
                ('published', models.CharField(blank=True, max_length=40)),
                ('source', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True, max_length=400)),
                ('retrieved', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SafetyScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='b1_street_safety',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='b2_road_safety',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='c1_utilities',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='c2_requests',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='e2_air',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='profile',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='district',
            name='s1_schools',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='s2_clinics',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='SafetyPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('fire_station', 'Fire station'), ('police_station', 'Police department'), ('police_post', 'Local police post'), ('lamp', 'Street lamp'), ('speed_camera', 'Speed camera'), ('cctv', 'CCTV camera')], max_length=20)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('source', models.CharField(choices=[('2gis', '2GIS directory'), ('osm', 'OpenStreetMap')], max_length=10)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_places', to='core.district')),
            ],
        ),
    ]
