# Generated by Django 6.1.1 on 2026-09-23 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_safety'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(unique=True)),
                ('births', models.PositiveIntegerField()),
                ('estimated', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='EducationScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='births_2024',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='EducationPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('school', 'School'), ('kindergarten', 'Kindergarten')], max_length=15)),
                ('subtype', models.CharField(blank=True, max_length=40)),
                ('public', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_places', to='core.district')),
            ],
        ),
    ]
