# Generated by Django 6.1.1 on 2026-09-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityServiceScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='docx_population_share',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='CityServiceStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('utility', models.CharField(choices=[('electricity', 'Electricity'), ('water', 'Water'), ('heating', 'Heating'), ('sewage', 'Sewage')], max_length=15)),
                ('category_name', models.CharField(max_length=120)),
                ('count', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['utility', 'year'],
                'unique_together': {('year', 'utility')},
            },
        ),
    ]
