# Generated by Django 6.1.1 on 2026-09-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cityservices'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=8)),
                ('text_hash', models.CharField(max_length=64)),
                ('source_text', models.TextField()),
                ('translated_text', models.TextField()),
            ],
            options={
                'unique_together': {('target', 'text_hash')},
            },
        ),
    ]
